language: node_js
node_js: "lts/*"
cache: yarn
install:
  - cd app && yarn
  - cd ../functions && yarn
script:
  - yarn lint # "test" cloud functions
  - cd ../app && yarn lint # "test" client
before_deploy:
  - yarn build # build static site
  - cd .. # deploy needs to be run from root
deploy:
  provider: firebase
  token: $FIREBASE_TOKEN
  project: creuna-dashboard
  on:
    branch: master
  skip_cleanup: true
# notifications:
#   webhooks:
#     on_start: always
#     urls:
#       - secure: "<Encrypted URL here>"
