language: node_js
node_js: "lts/*"
cache: yarn
install:
  - cd app && yarn
script:
  - yarn test
before_deploy: cd .. # go back to root before deploying
deploy:
  provider: firebase
  token: $FIREBASE_TOKEN
  project: creuna-dashboard
  on:
    branch: master
  skip_cleanup: true